### ISSUE TITLE
Link to bintray repo is broken

### ISSUE THREAD

**Issue by memsharded** [jonico/zenofgithub#1]
You are linking the API endpoint, you probably want to link the https://bintray.com/conan-jonico URL instead.

Great job!

My zen, built in Win10, VS14 :) :) :)

```text
            MMM.           .MMM
               MMMMMMMMMMMMMMMMMMM
               MMMMMMMMMMMMMMMMMMM      _____________________________________________
              MMMMMMMMMMMMMMMMMMMMM    |                                             |
             MMMMMMMMMMMMMMMMMMMMMMM   | Half measures are as bad as nothing at all. |
            MMMMMMMMMMMMMMMMMMMMMMMM   |_   _________________________________________|
            MMMM::- -:::::::- -::MMMM    |/
             MM~:~ 00~:::::~ 00~:~MM
        .. MMMMM::.00:::+:::.00::MMMMM ..
              .MM::::: ._. :::::MM.
                 MMMM;:::::;MMMM
          -MM        MMMMMMM
          ^  M+     MMMMMMMMM
              MMMMMMM MM MM MM
                   MM MM MM MM
                   MM MM MM MM
                .~~MM~MM~MM~MM~~.
             ~~~~MM:~MM~~~MM~:MM~~~~
            ~~~~~~==~==~~~==~==~~~~~~
             ~~~~~~==~==~==~==~~~~~~
                 :~==~==~==~==~~
```

**Comment by jonico** [comment]
Hi @memsharded, BinTray actually suggested that endpoint to me:

![image](https://user-images.githubusercontent.com/1872314/27044115-ca39171a-4f9c-11e7-84d6-e72f6b9b2a28.png)

It also worked for all my coworkers, should I really change it?

**Comment by memsharded** [comment]
Ah, no sorry, you are right. I was confused while clicking on the link, not read the full text. I'd probably just remove the hyperlink in the text, as it is not navigable: https://github.com/jonico/zenofgithub/pull/2

**Comment by jonico** [comment]
@memsharded: thanks, merged your PR, closing this one
